<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Foxtamp.MLSimpleSample</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\MLCoreModule\MLCoreModule.csproj" />
      <ProjectReference Include="..\MLModelCodec\MLModelCodec.csproj" />
    </ItemGroup>

</Project>
