// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace SentisFlatBuffer
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public enum ScalarType : sbyte
{
  FLOAT = 0,
  INT = 1,
  BYTE = 2,
  SHORT = 3,
};

public enum TensorShapeDynamism : sbyte
{
  STATIC = 0,
  DYNAMIC_UNBOUND = 1,
};

public enum SymbolicDim : byte
{
  NONE = 0,
  Int = 1,
  Byte = 2,
};



static public class SymbolicDimVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((SymbolicDim)typeId)
    {
      case SymbolicDim.Int:
        result = SentisFlatBuffer.IntVerify.Verify(verifier, tablePos);
        break;
      case SymbolicDim.Byte:
        result = SentisFlatBuffer.ByteVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public enum KernelTypes : byte
{
  NONE = 0,
  Null = 1,
  Int = 2,
  Float = 3,
  Bool = 4,
  Byte = 5,
  Tensor = 6,
  String = 7,
  IntList = 8,
  FloatList = 9,
  BoolList = 10,
};



static public class KernelTypesVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((KernelTypes)typeId)
    {
      case KernelTypes.Null:
        result = SentisFlatBuffer.NullVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Int:
        result = SentisFlatBuffer.IntVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Float:
        result = SentisFlatBuffer.FloatVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Bool:
        result = SentisFlatBuffer.BoolVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Byte:
        result = SentisFlatBuffer.ByteVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.Tensor:
        result = SentisFlatBuffer.TensorVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.String:
        result = SentisFlatBuffer.StringVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.IntList:
        result = SentisFlatBuffer.IntListVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.FloatList:
        result = SentisFlatBuffer.FloatListVerify.Verify(verifier, tablePos);
        break;
      case KernelTypes.BoolList:
        result = SentisFlatBuffer.BoolListVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public enum InstructionArguments : byte
{
  NONE = 0,
  KernelCall = 1,
};



static public class InstructionArgumentsVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, byte typeId, uint tablePos)
  {
    bool result = true;
    switch((InstructionArguments)typeId)
    {
      case InstructionArguments.KernelCall:
        result = SentisFlatBuffer.KernelCallVerify.Verify(verifier, tablePos);
        break;
      default: result = true;
        break;
    }
    return result;
  }
}

public enum BackendType : sbyte
{
  CPU = 0,
};

public struct Null : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Null GetRootAsNull(ByteBuffer _bb) { return GetRootAsNull(_bb, new Null()); }
  public static Null GetRootAsNull(ByteBuffer _bb, Null obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Null __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }


  public static void StartNull(FlatBufferBuilder builder) { builder.StartTable(0); }
  public static Offset<SentisFlatBuffer.Null> EndNull(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Null>(o);
  }
}


static public class NullVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Byte : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Byte GetRootAsByte(ByteBuffer _bb) { return GetRootAsByte(_bb, new Byte()); }
  public static Byte GetRootAsByte(ByteBuffer _bb, Byte obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Byte __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte ByteVal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(o + __p.bb_pos) : (byte)0; } }

  public static Offset<SentisFlatBuffer.Byte> CreateByte(FlatBufferBuilder builder,
      byte byte_val = 0) {
    builder.StartTable(1);
    Byte.AddByteVal(builder, byte_val);
    return Byte.EndByte(builder);
  }

  public static void StartByte(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddByteVal(FlatBufferBuilder builder, byte byteVal) { builder.AddByte(0, byteVal, 0); }
  public static Offset<SentisFlatBuffer.Byte> EndByte(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Byte>(o);
  }
}


static public class ByteVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ByteVal*/, 1 /*byte*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Short : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Short GetRootAsShort(ByteBuffer _bb) { return GetRootAsShort(_bb, new Short()); }
  public static Short GetRootAsShort(ByteBuffer _bb, Short obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Short __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public short ShortVal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetShort(o + __p.bb_pos) : (short)0; } }

  public static Offset<SentisFlatBuffer.Short> CreateShort(FlatBufferBuilder builder,
      short short_val = 0) {
    builder.StartTable(1);
    Short.AddShortVal(builder, short_val);
    return Short.EndShort(builder);
  }

  public static void StartShort(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddShortVal(FlatBufferBuilder builder, short shortVal) { builder.AddShort(0, shortVal, 0); }
  public static Offset<SentisFlatBuffer.Short> EndShort(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Short>(o);
  }
}


static public class ShortVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ShortVal*/, 2 /*short*/, 2, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Int : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Int GetRootAsInt(ByteBuffer _bb) { return GetRootAsInt(_bb, new Int()); }
  public static Int GetRootAsInt(ByteBuffer _bb, Int obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Int __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int IntVal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<SentisFlatBuffer.Int> CreateInt(FlatBufferBuilder builder,
      int int_val = 0) {
    builder.StartTable(1);
    Int.AddIntVal(builder, int_val);
    return Int.EndInt(builder);
  }

  public static void StartInt(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddIntVal(FlatBufferBuilder builder, int intVal) { builder.AddInt(0, intVal, 0); }
  public static Offset<SentisFlatBuffer.Int> EndInt(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Int>(o);
  }
}


static public class IntVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*IntVal*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Float : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Float GetRootAsFloat(ByteBuffer _bb) { return GetRootAsFloat(_bb, new Float()); }
  public static Float GetRootAsFloat(ByteBuffer _bb, Float obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Float __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float FloatVal { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<SentisFlatBuffer.Float> CreateFloat(FlatBufferBuilder builder,
      float float_val = 0.0f) {
    builder.StartTable(1);
    Float.AddFloatVal(builder, float_val);
    return Float.EndFloat(builder);
  }

  public static void StartFloat(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddFloatVal(FlatBufferBuilder builder, float floatVal) { builder.AddFloat(0, floatVal, 0.0f); }
  public static Offset<SentisFlatBuffer.Float> EndFloat(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Float>(o);
  }
}


static public class FloatVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*FloatVal*/, 4 /*float*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Bool : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Bool GetRootAsBool(ByteBuffer _bb) { return GetRootAsBool(_bb, new Bool()); }
  public static Bool GetRootAsBool(ByteBuffer _bb, Bool obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Bool __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool BoolVal { get { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<SentisFlatBuffer.Bool> CreateBool(FlatBufferBuilder builder,
      bool bool_val = false) {
    builder.StartTable(1);
    Bool.AddBoolVal(builder, bool_val);
    return Bool.EndBool(builder);
  }

  public static void StartBool(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddBoolVal(FlatBufferBuilder builder, bool boolVal) { builder.AddBool(0, boolVal, false); }
  public static Offset<SentisFlatBuffer.Bool> EndBool(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Bool>(o);
  }
}


static public class BoolVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*BoolVal*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct String : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static String GetRootAsString(ByteBuffer _bb) { return GetRootAsString(_bb, new String()); }
  public static String GetRootAsString(ByteBuffer _bb, String obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public String __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string StringVal { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStringValBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetStringValBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetStringValArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SentisFlatBuffer.String> CreateString(FlatBufferBuilder builder,
      StringOffset string_valOffset = default(StringOffset)) {
    builder.StartTable(1);
    String.AddStringVal(builder, string_valOffset);
    return String.EndString(builder);
  }

  public static void StartString(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStringVal(FlatBufferBuilder builder, StringOffset stringValOffset) { builder.AddOffset(0, stringValOffset.Value, 0); }
  public static Offset<SentisFlatBuffer.String> EndString(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.String>(o);
  }
}


static public class StringVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*StringVal*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct IntList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static IntList GetRootAsIntList(ByteBuffer _bb) { return GetRootAsIntList(_bb, new IntList()); }
  public static IntList GetRootAsIntList(ByteBuffer _bb, IntList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public IntList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Items(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetItemsBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetItemsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetItemsArray() { return __p.__vector_as_array<int>(4); }

  public static Offset<SentisFlatBuffer.IntList> CreateIntList(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    IntList.AddItems(builder, itemsOffset);
    return IntList.EndIntList(builder);
  }

  public static void StartIntList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.IntList> EndIntList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.IntList>(o);
  }
}


static public class IntListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Items*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct FloatList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static FloatList GetRootAsFloatList(ByteBuffer _bb) { return GetRootAsFloatList(_bb, new FloatList()); }
  public static FloatList GetRootAsFloatList(ByteBuffer _bb, FloatList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public FloatList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float Items(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(__p.__vector(o) + j * 4) : (float)0; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<float> GetItemsBytes() { return __p.__vector_as_span<float>(4, 4); }
#else
  public ArraySegment<byte>? GetItemsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public float[] GetItemsArray() { return __p.__vector_as_array<float>(4); }

  public static Offset<SentisFlatBuffer.FloatList> CreateFloatList(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    FloatList.AddItems(builder, itemsOffset);
    return FloatList.EndFloatList(builder);
  }

  public static void StartFloatList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddFloat(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, float[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<float> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<float>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.FloatList> EndFloatList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.FloatList>(o);
  }
}


static public class FloatListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Items*/, 4 /*float*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct BoolList : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BoolList GetRootAsBoolList(ByteBuffer _bb) { return GetRootAsBoolList(_bb, new BoolList()); }
  public static BoolList GetRootAsBoolList(ByteBuffer _bb, BoolList obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BoolList __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public bool Items(int j) { int o = __p.__offset(4); return o != 0 ? 0!=__p.bb.Get(__p.__vector(o) + j * 1) : false; }
  public int ItemsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<bool> GetItemsBytes() { return __p.__vector_as_span<bool>(4, 1); }
#else
  public ArraySegment<byte>? GetItemsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public bool[] GetItemsArray() { return __p.__vector_as_array<bool>(4); }

  public static Offset<SentisFlatBuffer.BoolList> CreateBoolList(FlatBufferBuilder builder,
      VectorOffset itemsOffset = default(VectorOffset)) {
    builder.StartTable(1);
    BoolList.AddItems(builder, itemsOffset);
    return BoolList.EndBoolList(builder);
  }

  public static void StartBoolList(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddItems(FlatBufferBuilder builder, VectorOffset itemsOffset) { builder.AddOffset(0, itemsOffset.Value, 0); }
  public static VectorOffset CreateItemsVector(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddBool(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, bool[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, ArraySegment<bool> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateItemsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<bool>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartItemsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SentisFlatBuffer.BoolList> EndBoolList(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.BoolList>(o);
  }
}


static public class BoolListVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Items*/, 1 /*bool*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EDim : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EDim GetRootAsEDim(ByteBuffer _bb) { return GetRootAsEDim(_bb, new EDim()); }
  public static EDim GetRootAsEDim(ByteBuffer _bb, EDim obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EDim __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SentisFlatBuffer.SymbolicDim ValType { get { int o = __p.__offset(4); return o != 0 ? (SentisFlatBuffer.SymbolicDim)__p.bb.Get(o + __p.bb_pos) : SentisFlatBuffer.SymbolicDim.NONE; } }
  public TTable? Val<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SentisFlatBuffer.Int ValAsInt() { return Val<SentisFlatBuffer.Int>().Value; }
  public SentisFlatBuffer.Byte ValAsByte() { return Val<SentisFlatBuffer.Byte>().Value; }

  public static Offset<SentisFlatBuffer.EDim> CreateEDim(FlatBufferBuilder builder,
      SentisFlatBuffer.SymbolicDim val_type = SentisFlatBuffer.SymbolicDim.NONE,
      int valOffset = 0) {
    builder.StartTable(2);
    EDim.AddVal(builder, valOffset);
    EDim.AddValType(builder, val_type);
    return EDim.EndEDim(builder);
  }

  public static void StartEDim(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValType(FlatBufferBuilder builder, SentisFlatBuffer.SymbolicDim valType) { builder.AddByte(0, (byte)valType, 0); }
  public static void AddVal(FlatBufferBuilder builder, int valOffset) { builder.AddOffset(1, valOffset, 0); }
  public static Offset<SentisFlatBuffer.EDim> EndEDim(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.EDim>(o);
  }
}


static public class EDimVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ValType*/, 1 /*SentisFlatBuffer.SymbolicDim*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Val*/, SentisFlatBuffer.SymbolicDimVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Tensor : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Tensor GetRootAsTensor(ByteBuffer _bb) { return GetRootAsTensor(_bb, new Tensor()); }
  public static Tensor GetRootAsTensor(ByteBuffer _bb, Tensor obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Tensor __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SentisFlatBuffer.ScalarType ScalarType { get { int o = __p.__offset(4); return o != 0 ? (SentisFlatBuffer.ScalarType)__p.bb.GetSbyte(o + __p.bb_pos) : SentisFlatBuffer.ScalarType.FLOAT; } }
  public int LengthByte { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int FixedSizes(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int FixedSizesLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetFixedSizesBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetFixedSizesBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetFixedSizesArray() { return __p.__vector_as_array<int>(8); }
  public uint ConstantBufferIdx { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public int StorageOffset { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public SentisFlatBuffer.TensorShapeDynamism ShapeDynamism { get { int o = __p.__offset(14); return o != 0 ? (SentisFlatBuffer.TensorShapeDynamism)__p.bb.GetSbyte(o + __p.bb_pos) : SentisFlatBuffer.TensorShapeDynamism.STATIC; } }
  public SentisFlatBuffer.EDim? DynamicSizes(int j) { int o = __p.__offset(16); return o != 0 ? (SentisFlatBuffer.EDim?)(new SentisFlatBuffer.EDim()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DynamicSizesLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  public bool HasDynamicRank { get { int o = __p.__offset(18); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<SentisFlatBuffer.Tensor> CreateTensor(FlatBufferBuilder builder,
      SentisFlatBuffer.ScalarType scalar_type = SentisFlatBuffer.ScalarType.FLOAT,
      int length_byte = 0,
      VectorOffset fixed_sizesOffset = default(VectorOffset),
      uint constant_buffer_idx = 0,
      int storage_offset = 0,
      SentisFlatBuffer.TensorShapeDynamism shape_dynamism = SentisFlatBuffer.TensorShapeDynamism.STATIC,
      VectorOffset dynamic_sizesOffset = default(VectorOffset),
      bool has_dynamic_rank = false) {
    builder.StartTable(8);
    Tensor.AddDynamicSizes(builder, dynamic_sizesOffset);
    Tensor.AddStorageOffset(builder, storage_offset);
    Tensor.AddConstantBufferIdx(builder, constant_buffer_idx);
    Tensor.AddFixedSizes(builder, fixed_sizesOffset);
    Tensor.AddLengthByte(builder, length_byte);
    Tensor.AddHasDynamicRank(builder, has_dynamic_rank);
    Tensor.AddShapeDynamism(builder, shape_dynamism);
    Tensor.AddScalarType(builder, scalar_type);
    return Tensor.EndTensor(builder);
  }

  public static void StartTensor(FlatBufferBuilder builder) { builder.StartTable(8); }
  public static void AddScalarType(FlatBufferBuilder builder, SentisFlatBuffer.ScalarType scalarType) { builder.AddSbyte(0, (sbyte)scalarType, 0); }
  public static void AddLengthByte(FlatBufferBuilder builder, int lengthByte) { builder.AddInt(1, lengthByte, 0); }
  public static void AddFixedSizes(FlatBufferBuilder builder, VectorOffset fixedSizesOffset) { builder.AddOffset(2, fixedSizesOffset.Value, 0); }
  public static VectorOffset CreateFixedSizesVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateFixedSizesVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFixedSizesVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateFixedSizesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartFixedSizesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddConstantBufferIdx(FlatBufferBuilder builder, uint constantBufferIdx) { builder.AddUint(3, constantBufferIdx, 0); }
  public static void AddStorageOffset(FlatBufferBuilder builder, int storageOffset) { builder.AddInt(4, storageOffset, 0); }
  public static void AddShapeDynamism(FlatBufferBuilder builder, SentisFlatBuffer.TensorShapeDynamism shapeDynamism) { builder.AddSbyte(5, (sbyte)shapeDynamism, 0); }
  public static void AddDynamicSizes(FlatBufferBuilder builder, VectorOffset dynamicSizesOffset) { builder.AddOffset(6, dynamicSizesOffset.Value, 0); }
  public static VectorOffset CreateDynamicSizesVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.EDim>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDynamicSizesVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.EDim>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDynamicSizesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.EDim>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateDynamicSizesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.EDim>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartDynamicSizesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHasDynamicRank(FlatBufferBuilder builder, bool hasDynamicRank) { builder.AddBool(7, hasDynamicRank, false); }
  public static Offset<SentisFlatBuffer.Tensor> EndTensor(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Tensor>(o);
  }
}


static public class TensorVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ScalarType*/, 1 /*SentisFlatBuffer.ScalarType*/, 1, false)
      && verifier.VerifyField(tablePos, 6 /*LengthByte*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*FixedSizes*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 10 /*ConstantBufferIdx*/, 4 /*uint*/, 4, false)
      && verifier.VerifyField(tablePos, 12 /*StorageOffset*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 14 /*ShapeDynamism*/, 1 /*SentisFlatBuffer.TensorShapeDynamism*/, 1, false)
      && verifier.VerifyVectorOfTables(tablePos, 16 /*DynamicSizes*/, SentisFlatBuffer.EDimVerify.Verify, false)
      && verifier.VerifyField(tablePos, 18 /*HasDynamicRank*/, 1 /*bool*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct EValue : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static EValue GetRootAsEValue(ByteBuffer _bb) { return GetRootAsEValue(_bb, new EValue()); }
  public static EValue GetRootAsEValue(ByteBuffer _bb, EValue obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public EValue __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SentisFlatBuffer.KernelTypes ValType { get { int o = __p.__offset(4); return o != 0 ? (SentisFlatBuffer.KernelTypes)__p.bb.Get(o + __p.bb_pos) : SentisFlatBuffer.KernelTypes.NONE; } }
  public TTable? Val<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SentisFlatBuffer.Null ValAsNull() { return Val<SentisFlatBuffer.Null>().Value; }
  public SentisFlatBuffer.Int ValAsInt() { return Val<SentisFlatBuffer.Int>().Value; }
  public SentisFlatBuffer.Float ValAsFloat() { return Val<SentisFlatBuffer.Float>().Value; }
  public SentisFlatBuffer.Bool ValAsBool() { return Val<SentisFlatBuffer.Bool>().Value; }
  public SentisFlatBuffer.Byte ValAsByte() { return Val<SentisFlatBuffer.Byte>().Value; }
  public SentisFlatBuffer.Tensor ValAsTensor() { return Val<SentisFlatBuffer.Tensor>().Value; }
  public SentisFlatBuffer.String ValAsString() { return Val<SentisFlatBuffer.String>().Value; }
  public SentisFlatBuffer.IntList ValAsIntList() { return Val<SentisFlatBuffer.IntList>().Value; }
  public SentisFlatBuffer.FloatList ValAsFloatList() { return Val<SentisFlatBuffer.FloatList>().Value; }
  public SentisFlatBuffer.BoolList ValAsBoolList() { return Val<SentisFlatBuffer.BoolList>().Value; }

  public static Offset<SentisFlatBuffer.EValue> CreateEValue(FlatBufferBuilder builder,
      SentisFlatBuffer.KernelTypes val_type = SentisFlatBuffer.KernelTypes.NONE,
      int valOffset = 0) {
    builder.StartTable(2);
    EValue.AddVal(builder, valOffset);
    EValue.AddValType(builder, val_type);
    return EValue.EndEValue(builder);
  }

  public static void StartEValue(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddValType(FlatBufferBuilder builder, SentisFlatBuffer.KernelTypes valType) { builder.AddByte(0, (byte)valType, 0); }
  public static void AddVal(FlatBufferBuilder builder, int valOffset) { builder.AddOffset(1, valOffset, 0); }
  public static Offset<SentisFlatBuffer.EValue> EndEValue(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.EValue>(o);
  }
}


static public class EValueVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*ValType*/, 1 /*SentisFlatBuffer.KernelTypes*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*Val*/, SentisFlatBuffer.KernelTypesVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Operator : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Operator GetRootAsOperator(ByteBuffer _bb) { return GetRootAsOperator(_bb, new Operator()); }
  public static Operator GetRootAsOperator(ByteBuffer _bb, Operator obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Operator __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SentisFlatBuffer.Operator> CreateOperator(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset)) {
    builder.StartTable(1);
    Operator.AddName(builder, nameOffset);
    return Operator.EndOperator(builder);
  }

  public static void StartOperator(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static Offset<SentisFlatBuffer.Operator> EndOperator(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Operator>(o);
  }
}


static public class OperatorVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct KernelCall : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static KernelCall GetRootAsKernelCall(ByteBuffer _bb) { return GetRootAsKernelCall(_bb, new KernelCall()); }
  public static KernelCall GetRootAsKernelCall(ByteBuffer _bb, KernelCall obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public KernelCall __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int OpIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Args(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ArgsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetArgsBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetArgsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetArgsArray() { return __p.__vector_as_array<int>(6); }

  public static Offset<SentisFlatBuffer.KernelCall> CreateKernelCall(FlatBufferBuilder builder,
      int op_index = 0,
      VectorOffset argsOffset = default(VectorOffset)) {
    builder.StartTable(2);
    KernelCall.AddArgs(builder, argsOffset);
    KernelCall.AddOpIndex(builder, op_index);
    return KernelCall.EndKernelCall(builder);
  }

  public static void StartKernelCall(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddOpIndex(FlatBufferBuilder builder, int opIndex) { builder.AddInt(0, opIndex, 0); }
  public static void AddArgs(FlatBufferBuilder builder, VectorOffset argsOffset) { builder.AddOffset(1, argsOffset.Value, 0); }
  public static VectorOffset CreateArgsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateArgsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartArgsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.KernelCall> EndKernelCall(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.KernelCall>(o);
  }
}


static public class KernelCallVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*OpIndex*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Args*/, 4 /*int*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Instruction : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Instruction GetRootAsInstruction(ByteBuffer _bb) { return GetRootAsInstruction(_bb, new Instruction()); }
  public static Instruction GetRootAsInstruction(ByteBuffer _bb, Instruction obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Instruction __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public SentisFlatBuffer.InstructionArguments InstrArgsType { get { int o = __p.__offset(4); return o != 0 ? (SentisFlatBuffer.InstructionArguments)__p.bb.Get(o + __p.bb_pos) : SentisFlatBuffer.InstructionArguments.NONE; } }
  public TTable? InstrArgs<TTable>() where TTable : struct, IFlatbufferObject { int o = __p.__offset(6); return o != 0 ? (TTable?)__p.__union<TTable>(o + __p.bb_pos) : null; }
  public SentisFlatBuffer.KernelCall InstrArgsAsKernelCall() { return InstrArgs<SentisFlatBuffer.KernelCall>().Value; }

  public static Offset<SentisFlatBuffer.Instruction> CreateInstruction(FlatBufferBuilder builder,
      SentisFlatBuffer.InstructionArguments instr_args_type = SentisFlatBuffer.InstructionArguments.NONE,
      int instr_argsOffset = 0) {
    builder.StartTable(2);
    Instruction.AddInstrArgs(builder, instr_argsOffset);
    Instruction.AddInstrArgsType(builder, instr_args_type);
    return Instruction.EndInstruction(builder);
  }

  public static void StartInstruction(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddInstrArgsType(FlatBufferBuilder builder, SentisFlatBuffer.InstructionArguments instrArgsType) { builder.AddByte(0, (byte)instrArgsType, 0); }
  public static void AddInstrArgs(FlatBufferBuilder builder, int instrArgsOffset) { builder.AddOffset(1, instrArgsOffset, 0); }
  public static Offset<SentisFlatBuffer.Instruction> EndInstruction(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Instruction>(o);
  }
}


static public class InstructionVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*InstrArgsType*/, 1 /*SentisFlatBuffer.InstructionArguments*/, 1, false)
      && verifier.VerifyUnion(tablePos, 4, 6 /*InstrArgs*/, SentisFlatBuffer.InstructionArgumentsVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Chain : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Chain GetRootAsChain(ByteBuffer _bb) { return GetRootAsChain(_bb, new Chain()); }
  public static Chain GetRootAsChain(ByteBuffer _bb, Chain obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Chain __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Inputs(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int InputsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetInputsBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetInputsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetInputsArray() { return __p.__vector_as_array<int>(4); }
  public int Outputs(int j) { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int OutputsLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetOutputsBytes() { return __p.__vector_as_span<int>(6, 4); }
#else
  public ArraySegment<byte>? GetOutputsBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public int[] GetOutputsArray() { return __p.__vector_as_array<int>(6); }
  public SentisFlatBuffer.Instruction? Instructions(int j) { int o = __p.__offset(8); return o != 0 ? (SentisFlatBuffer.Instruction?)(new SentisFlatBuffer.Instruction()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int InstructionsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SentisFlatBuffer.Chain> CreateChain(FlatBufferBuilder builder,
      VectorOffset inputsOffset = default(VectorOffset),
      VectorOffset outputsOffset = default(VectorOffset),
      VectorOffset instructionsOffset = default(VectorOffset)) {
    builder.StartTable(3);
    Chain.AddInstructions(builder, instructionsOffset);
    Chain.AddOutputs(builder, outputsOffset);
    Chain.AddInputs(builder, inputsOffset);
    return Chain.EndChain(builder);
  }

  public static void StartChain(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddInputs(FlatBufferBuilder builder, VectorOffset inputsOffset) { builder.AddOffset(0, inputsOffset.Value, 0); }
  public static VectorOffset CreateInputsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInputsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOutputs(FlatBufferBuilder builder, VectorOffset outputsOffset) { builder.AddOffset(1, outputsOffset.Value, 0); }
  public static VectorOffset CreateOutputsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOutputsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInstructions(FlatBufferBuilder builder, VectorOffset instructionsOffset) { builder.AddOffset(2, instructionsOffset.Value, 0); }
  public static VectorOffset CreateInstructionsVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Instruction>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInstructionsVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Instruction>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInstructionsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.Instruction>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInstructionsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.Instruction>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInstructionsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.Chain> EndChain(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Chain>(o);
  }
}


static public class ChainVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Inputs*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfData(tablePos, 6 /*Outputs*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 8 /*Instructions*/, SentisFlatBuffer.InstructionVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct BackendPartitioning : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static BackendPartitioning GetRootAsBackendPartitioning(ByteBuffer _bb) { return GetRootAsBackendPartitioning(_bb, new BackendPartitioning()); }
  public static BackendPartitioning GetRootAsBackendPartitioning(ByteBuffer _bb, BackendPartitioning obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public BackendPartitioning __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Chains(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int ChainsLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetChainsBytes() { return __p.__vector_as_span<int>(4, 4); }
#else
  public ArraySegment<byte>? GetChainsBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public int[] GetChainsArray() { return __p.__vector_as_array<int>(4); }
  public SentisFlatBuffer.BackendType Backend { get { int o = __p.__offset(6); return o != 0 ? (SentisFlatBuffer.BackendType)__p.bb.GetSbyte(o + __p.bb_pos) : SentisFlatBuffer.BackendType.CPU; } }

  public static Offset<SentisFlatBuffer.BackendPartitioning> CreateBackendPartitioning(FlatBufferBuilder builder,
      VectorOffset chainsOffset = default(VectorOffset),
      SentisFlatBuffer.BackendType backend = SentisFlatBuffer.BackendType.CPU) {
    builder.StartTable(2);
    BackendPartitioning.AddChains(builder, chainsOffset);
    BackendPartitioning.AddBackend(builder, backend);
    return BackendPartitioning.EndBackendPartitioning(builder);
  }

  public static void StartBackendPartitioning(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddChains(FlatBufferBuilder builder, VectorOffset chainsOffset) { builder.AddOffset(0, chainsOffset.Value, 0); }
  public static VectorOffset CreateChainsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChainsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBackend(FlatBufferBuilder builder, SentisFlatBuffer.BackendType backend) { builder.AddSbyte(1, (sbyte)backend, 0); }
  public static Offset<SentisFlatBuffer.BackendPartitioning> EndBackendPartitioning(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.BackendPartitioning>(o);
  }
}


static public class BackendPartitioningVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Chains*/, 4 /*int*/, false)
      && verifier.VerifyField(tablePos, 6 /*Backend*/, 1 /*SentisFlatBuffer.BackendType*/, 1, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct ExecutionPlan : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static ExecutionPlan GetRootAsExecutionPlan(ByteBuffer _bb) { return GetRootAsExecutionPlan(_bb, new ExecutionPlan()); }
  public static ExecutionPlan GetRootAsExecutionPlan(ByteBuffer _bb, ExecutionPlan obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public ExecutionPlan __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public SentisFlatBuffer.EValue? Values(int j) { int o = __p.__offset(6); return o != 0 ? (SentisFlatBuffer.EValue?)(new SentisFlatBuffer.EValue()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ValuesLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Inputs(int j) { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int InputsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetInputsBytes() { return __p.__vector_as_span<int>(8, 4); }
#else
  public ArraySegment<byte>? GetInputsBytes() { return __p.__vector_as_arraysegment(8); }
#endif
  public int[] GetInputsArray() { return __p.__vector_as_array<int>(8); }
  public string InputsName(int j) { int o = __p.__offset(10); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int InputsNameLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Outputs(int j) { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(__p.__vector(o) + j * 4) : (int)0; }
  public int OutputsLength { get { int o = __p.__offset(12); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<int> GetOutputsBytes() { return __p.__vector_as_span<int>(12, 4); }
#else
  public ArraySegment<byte>? GetOutputsBytes() { return __p.__vector_as_arraysegment(12); }
#endif
  public int[] GetOutputsArray() { return __p.__vector_as_array<int>(12); }
  public string OutputsName(int j) { int o = __p.__offset(14); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int OutputsNameLength { get { int o = __p.__offset(14); return o != 0 ? __p.__vector_len(o) : 0; } }
  public SentisFlatBuffer.Chain? Chains(int j) { int o = __p.__offset(16); return o != 0 ? (SentisFlatBuffer.Chain?)(new SentisFlatBuffer.Chain()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int ChainsLength { get { int o = __p.__offset(16); return o != 0 ? __p.__vector_len(o) : 0; } }
  public SentisFlatBuffer.Operator? Operators(int j) { int o = __p.__offset(18); return o != 0 ? (SentisFlatBuffer.Operator?)(new SentisFlatBuffer.Operator()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int OperatorsLength { get { int o = __p.__offset(18); return o != 0 ? __p.__vector_len(o) : 0; } }
  public SentisFlatBuffer.BackendPartitioning? BackendPartitioning { get { int o = __p.__offset(20); return o != 0 ? (SentisFlatBuffer.BackendPartitioning?)(new SentisFlatBuffer.BackendPartitioning()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public string SymbolicDimNames(int j) { int o = __p.__offset(22); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int SymbolicDimNamesLength { get { int o = __p.__offset(22); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SentisFlatBuffer.ExecutionPlan> CreateExecutionPlan(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      VectorOffset valuesOffset = default(VectorOffset),
      VectorOffset inputsOffset = default(VectorOffset),
      VectorOffset inputs_nameOffset = default(VectorOffset),
      VectorOffset outputsOffset = default(VectorOffset),
      VectorOffset outputs_nameOffset = default(VectorOffset),
      VectorOffset chainsOffset = default(VectorOffset),
      VectorOffset operatorsOffset = default(VectorOffset),
      Offset<SentisFlatBuffer.BackendPartitioning> backend_partitioningOffset = default(Offset<SentisFlatBuffer.BackendPartitioning>),
      VectorOffset symbolic_dim_namesOffset = default(VectorOffset)) {
    builder.StartTable(10);
    ExecutionPlan.AddSymbolicDimNames(builder, symbolic_dim_namesOffset);
    ExecutionPlan.AddBackendPartitioning(builder, backend_partitioningOffset);
    ExecutionPlan.AddOperators(builder, operatorsOffset);
    ExecutionPlan.AddChains(builder, chainsOffset);
    ExecutionPlan.AddOutputsName(builder, outputs_nameOffset);
    ExecutionPlan.AddOutputs(builder, outputsOffset);
    ExecutionPlan.AddInputsName(builder, inputs_nameOffset);
    ExecutionPlan.AddInputs(builder, inputsOffset);
    ExecutionPlan.AddValues(builder, valuesOffset);
    ExecutionPlan.AddName(builder, nameOffset);
    return ExecutionPlan.EndExecutionPlan(builder);
  }

  public static void StartExecutionPlan(FlatBufferBuilder builder) { builder.StartTable(10); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddValues(FlatBufferBuilder builder, VectorOffset valuesOffset) { builder.AddOffset(1, valuesOffset.Value, 0); }
  public static VectorOffset CreateValuesVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.EValue>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.EValue>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.EValue>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateValuesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.EValue>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartValuesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInputs(FlatBufferBuilder builder, VectorOffset inputsOffset) { builder.AddOffset(2, inputsOffset.Value, 0); }
  public static VectorOffset CreateInputsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInputsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddInputsName(FlatBufferBuilder builder, VectorOffset inputsNameOffset) { builder.AddOffset(3, inputsNameOffset.Value, 0); }
  public static VectorOffset CreateInputsNameVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateInputsNameVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsNameVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateInputsNameVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartInputsNameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOutputs(FlatBufferBuilder builder, VectorOffset outputsOffset) { builder.AddOffset(4, outputsOffset.Value, 0); }
  public static VectorOffset CreateOutputsVector(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddInt(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, int[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, ArraySegment<int> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<int>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOutputsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOutputsName(FlatBufferBuilder builder, VectorOffset outputsNameOffset) { builder.AddOffset(5, outputsNameOffset.Value, 0); }
  public static VectorOffset CreateOutputsNameVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOutputsNameVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsNameVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOutputsNameVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOutputsNameVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddChains(FlatBufferBuilder builder, VectorOffset chainsOffset) { builder.AddOffset(6, chainsOffset.Value, 0); }
  public static VectorOffset CreateChainsVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Chain>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Chain>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.Chain>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateChainsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.Chain>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartChainsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddOperators(FlatBufferBuilder builder, VectorOffset operatorsOffset) { builder.AddOffset(7, operatorsOffset.Value, 0); }
  public static VectorOffset CreateOperatorsVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Operator>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateOperatorsVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Operator>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOperatorsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.Operator>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateOperatorsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.Operator>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartOperatorsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddBackendPartitioning(FlatBufferBuilder builder, Offset<SentisFlatBuffer.BackendPartitioning> backendPartitioningOffset) { builder.AddOffset(8, backendPartitioningOffset.Value, 0); }
  public static void AddSymbolicDimNames(FlatBufferBuilder builder, VectorOffset symbolicDimNamesOffset) { builder.AddOffset(9, symbolicDimNamesOffset.Value, 0); }
  public static VectorOffset CreateSymbolicDimNamesVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSymbolicDimNamesVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSymbolicDimNamesVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSymbolicDimNamesVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSymbolicDimNamesVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.ExecutionPlan> EndExecutionPlan(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.ExecutionPlan>(o);
  }
}


static public class ExecutionPlanVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyString(tablePos, 4 /*Name*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 6 /*Values*/, SentisFlatBuffer.EValueVerify.Verify, false)
      && verifier.VerifyVectorOfData(tablePos, 8 /*Inputs*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 10 /*InputsName*/, false)
      && verifier.VerifyVectorOfData(tablePos, 12 /*Outputs*/, 4 /*int*/, false)
      && verifier.VerifyVectorOfStrings(tablePos, 14 /*OutputsName*/, false)
      && verifier.VerifyVectorOfTables(tablePos, 16 /*Chains*/, SentisFlatBuffer.ChainVerify.Verify, false)
      && verifier.VerifyVectorOfTables(tablePos, 18 /*Operators*/, SentisFlatBuffer.OperatorVerify.Verify, false)
      && verifier.VerifyTable(tablePos, 20 /*BackendPartitioning*/, SentisFlatBuffer.BackendPartitioningVerify.Verify, false)
      && verifier.VerifyVectorOfStrings(tablePos, 22 /*SymbolicDimNames*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Buffer : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Buffer GetRootAsBuffer(ByteBuffer _bb) { return GetRootAsBuffer(_bb, new Buffer()); }
  public static Buffer GetRootAsBuffer(ByteBuffer _bb, Buffer obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Buffer __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public byte Storage(int j) { int o = __p.__offset(4); return o != 0 ? __p.bb.Get(__p.__vector(o) + j * 1) : (byte)0; }
  public int StorageLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }
#if ENABLE_SPAN_T
  public Span<byte> GetStorageBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetStorageBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetStorageArray() { return __p.__vector_as_array<byte>(4); }

  public static Offset<SentisFlatBuffer.Buffer> CreateBuffer(FlatBufferBuilder builder,
      VectorOffset storageOffset = default(VectorOffset)) {
    builder.StartTable(1);
    Buffer.AddStorage(builder, storageOffset);
    return Buffer.EndBuffer(builder);
  }

  public static void StartBuffer(FlatBufferBuilder builder) { builder.StartTable(1); }
  public static void AddStorage(FlatBufferBuilder builder, VectorOffset storageOffset) { builder.AddOffset(0, storageOffset.Value, 0); }
  public static VectorOffset CreateStorageVector(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); for (int i = data.Length - 1; i >= 0; i--) builder.AddByte(data[i]); return builder.EndVector(); }
  public static VectorOffset CreateStorageVectorBlock(FlatBufferBuilder builder, byte[] data) { builder.StartVector(1, data.Length, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStorageVectorBlock(FlatBufferBuilder builder, ArraySegment<byte> data) { builder.StartVector(1, data.Count, 1); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateStorageVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<byte>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartStorageVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(1, numElems, 1); }
  public static Offset<SentisFlatBuffer.Buffer> EndBuffer(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Buffer>(o);
  }
}


static public class BufferVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyVectorOfData(tablePos, 4 /*Storage*/, 1 /*byte*/, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct DataSegment : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static DataSegment GetRootAsDataSegment(ByteBuffer _bb) { return GetRootAsDataSegment(_bb, new DataSegment()); }
  public static DataSegment GetRootAsDataSegment(ByteBuffer _bb, DataSegment obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public DataSegment __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public ulong Offset { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }
  public ulong Size { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetUlong(o + __p.bb_pos) : (ulong)0; } }

  public static Offset<SentisFlatBuffer.DataSegment> CreateDataSegment(FlatBufferBuilder builder,
      ulong offset = 0,
      ulong size = 0) {
    builder.StartTable(2);
    DataSegment.AddSize(builder, size);
    DataSegment.AddOffset(builder, offset);
    return DataSegment.EndDataSegment(builder);
  }

  public static void StartDataSegment(FlatBufferBuilder builder) { builder.StartTable(2); }
  public static void AddOffset(FlatBufferBuilder builder, ulong offset) { builder.AddUlong(0, offset, 0); }
  public static void AddSize(FlatBufferBuilder builder, ulong size) { builder.AddUlong(1, size, 0); }
  public static Offset<SentisFlatBuffer.DataSegment> EndDataSegment(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.DataSegment>(o);
  }
}


static public class DataSegmentVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Offset*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyField(tablePos, 6 /*Size*/, 8 /*ulong*/, 8, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}
public struct Program : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_25_2_10(); }
  public static Program GetRootAsProgram(ByteBuffer _bb) { return GetRootAsProgram(_bb, new Program()); }
  public static Program GetRootAsProgram(ByteBuffer _bb, Program obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public static bool ProgramBufferHasIdentifier(ByteBuffer _bb) { return Table.__has_identifier(_bb, "STU1"); }
  public static bool VerifyProgram(ByteBuffer _bb) {Google.FlatBuffers.Verifier verifier = new Google.FlatBuffers.Verifier(_bb); return verifier.VerifyBuffer("STU1", false, ProgramVerify.Verify); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Program __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public uint Version { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public SentisFlatBuffer.ExecutionPlan? ExecutionPlan { get { int o = __p.__offset(6); return o != 0 ? (SentisFlatBuffer.ExecutionPlan?)(new SentisFlatBuffer.ExecutionPlan()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public uint SegmentsOffset { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetUint(o + __p.bb_pos) : (uint)0; } }
  public SentisFlatBuffer.DataSegment? Segments(int j) { int o = __p.__offset(10); return o != 0 ? (SentisFlatBuffer.DataSegment?)(new SentisFlatBuffer.DataSegment()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int SegmentsLength { get { int o = __p.__offset(10); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<SentisFlatBuffer.Program> CreateProgram(FlatBufferBuilder builder,
      uint version = 0,
      Offset<SentisFlatBuffer.ExecutionPlan> execution_planOffset = default(Offset<SentisFlatBuffer.ExecutionPlan>),
      uint segments_offset = 0,
      VectorOffset segmentsOffset = default(VectorOffset)) {
    builder.StartTable(4);
    Program.AddSegments(builder, segmentsOffset);
    Program.AddSegmentsOffset(builder, segments_offset);
    Program.AddExecutionPlan(builder, execution_planOffset);
    Program.AddVersion(builder, version);
    return Program.EndProgram(builder);
  }

  public static void StartProgram(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddVersion(FlatBufferBuilder builder, uint version) { builder.AddUint(0, version, 0); }
  public static void AddExecutionPlan(FlatBufferBuilder builder, Offset<SentisFlatBuffer.ExecutionPlan> executionPlanOffset) { builder.AddOffset(1, executionPlanOffset.Value, 0); }
  public static void AddSegmentsOffset(FlatBufferBuilder builder, uint segmentsOffset) { builder.AddUint(2, segmentsOffset, 0); }
  public static void AddSegments(FlatBufferBuilder builder, VectorOffset segmentsOffset) { builder.AddOffset(3, segmentsOffset.Value, 0); }
  public static VectorOffset CreateSegmentsVector(FlatBufferBuilder builder, Offset<SentisFlatBuffer.DataSegment>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateSegmentsVectorBlock(FlatBufferBuilder builder, Offset<SentisFlatBuffer.DataSegment>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSegmentsVectorBlock(FlatBufferBuilder builder, ArraySegment<Offset<SentisFlatBuffer.DataSegment>> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateSegmentsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<Offset<SentisFlatBuffer.DataSegment>>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartSegmentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<SentisFlatBuffer.Program> EndProgram(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<SentisFlatBuffer.Program>(o);
  }
  public static void FinishProgramBuffer(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Program> offset) { builder.Finish(offset.Value, "STU1"); }
  public static void FinishSizePrefixedProgramBuffer(FlatBufferBuilder builder, Offset<SentisFlatBuffer.Program> offset) { builder.FinishSizePrefixed(offset.Value, "STU1"); }
}


static public class ProgramVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Version*/, 4 /*uint*/, 4, false)
      && verifier.VerifyTable(tablePos, 6 /*ExecutionPlan*/, SentisFlatBuffer.ExecutionPlanVerify.Verify, false)
      && verifier.VerifyField(tablePos, 8 /*SegmentsOffset*/, 4 /*uint*/, 4, false)
      && verifier.VerifyVectorOfTables(tablePos, 10 /*Segments*/, SentisFlatBuffer.DataSegmentVerify.Verify, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
