<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Foxtamp.MLCoreModule</RootNamespace>
    </PropertyGroup>

    <!-- Mac arm64 の場合のみ 0.105.1 -->
    <ItemGroup Condition="$([System.OperatingSystem]::IsMacOS())">
        <PackageReference Include="TorchSharp-cpu" Version="0.105.1" />
    </ItemGroup>

    <!-- それ以外は 0.105.2 -->
    <ItemGroup Condition="!$([System.OperatingSystem]::IsMacOS())">
        <PackageReference Include="TorchSharp-cpu" Version="0.105.2" />
    </ItemGroup>

</Project>
