<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Foxtamp.MjlogReplayer</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\MjlogReader\MjlogReader.csproj" />
    </ItemGroup>

</Project>
